image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 473.66338,    0.     ,  304.84389,
            0.     ,  476.26669,  201.08269,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.151775, -0.165566, -0.000982, -0.002355, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 490.11395,    0.     ,  303.29422,    0.     ,
            0.     ,  493.36469,  200.58533,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
